### ISSUE TITLE
What are the thresholds for depth confidence filter?

### ISSUE THREAD

**Issue by AlbertHuyb** [ewrfcas/MVSFormer#11]
Thanks for the nice work!

As mentioned in the paper, the depth maps are filtered by certain thresholds. 

Specifically, how should I set the `prob_threshold` parameters in [depthfusion.py](https://github.com/YoYo000/MVSNet/blob/master/mvsnet/depthfusion.py) for the tnt intermediate and advanced dataset to reproduce results in the paper?

Moreover, could you please provide the post-processing steps that prepare the submission to TNT official evaluation?

**Comment by ewrfcas** [comment]
Thanks. You could follow the instruction of README to reproduce the results.
prob_threshold/conf should be set with 0.5.
You could follow MVSNet to calculate the view similarity for more source views, but the performance gap is not too large.
