### ISSUE TITLE
Testing on DTU

### ISSUE THREAD

**Issue by karimcossentini** [ewrfcas/MVSFormer#16]
I got this error when testing on DTU: 
![image](https://github.com/ewrfcas/MVSFormer/assets/63617899/1cad3021-5e2c-4785-864c-f0cf96e37698)
it seems that this issue is resolved in an updated version of timm (0.9.2), but when upgrading it, another error occurs:
![image](https://github.com/ewrfcas/MVSFormer/assets/63617899/f63032a4-7786-4077-8bc4-80ed793655d4)
Any suggestion on how to fix this? 
Thanks

**Comment by ewrfcas** [comment]
See requirements.txt. We need timm==0.3.2.

**Comment by karimcossentini** [comment]
When installing the requirements.txt with timm==0.3.2, the first error of "cannot import name container_abcs"  occurs :(

**Comment by ewrfcas** [comment]
It should be caused by the pytorch version.
You could try to use "from torch._six import container_abcs" instead of "import collections.abc as container_abcs" or vice versa.

**Comment by karimcossentini** [comment]
It worked, thanks :)
