### ISSUE TITLE
您好，我运行了您的demo，但有一个问题想咨询您

### ISSUE THREAD

**Issue by x-ray990011** [ewrfcas/MVSFormer#18]
您的depths_raw是怎么生成的，如果我使用自建数据集，我如何获取depths_raw

**Comment by ewrfcas** [comment]
depths_raw是ground-truth的深度图，一般是由深度相机扫描，或者有对应真实mesh得到的

**Comment by x-ray990011** [comment]
> depths_raw是ground-truth的深度图，一般是由深度相机扫描，或者有对应真实mesh得到的

我如果是普通相机拍摄的照片，那我该如何获取depths_raw呢，我看dtu数据集本身也未带depths_raw，您是如何操作获取的呢，感谢您的回复
