### ISSUE TITLE
Lots of noise in output ply in tnt dataset

### ISSUE THREAD

**Issue by CC9310** [ewrfcas/MVSFormer#20]
Thanks for the author's great work.
Following the tnt test instruction, Lots of noise in the output ply
![2023-06-06_195304](https://github.com/ewrfcas/MVSFormer/assets/40813751/f33570f9-8a07-420c-a427-4244b9fb3981)
bash: 
CUDA_VISIBLE_DEVICES=0 python test.py --dataset tt --batch_size 1 --testpath /data/tankandtemples/intermediate/ \
                                                    --testlist ./lists/tanksandtemples/intermediate.txt \
                                                    --resume "/home/methods/MVSFormer/pretrained_weights/MVSFormer/best.pth" \
                                                    --outdir /data4/trained_models/MVSFormer_tnt_nview10/ \
                                                    --interval_scale 1.0 --num_view 10 --numdepth 256 --max_h 1088 --max_w 1920 \
                                                    --filter_method dpcd --prob_threshold 0.5,0.5,0.5,0.5 \
                                                    --use_short_range --combine_conf --tmps 5.0,5.0,5.0,1.0
Do the author has any idea to solve the problem?

**Comment by ewrfcas** [comment]
Hi, we recommend using MVSFormer-blended to evaluate Tanks and Temples.

**Comment by CC9310** [comment]
Thanks for quick reply :-). While, after using MVSFormer-Blended/best.pth with src_view 10, the recons point cloud also very noise(I didn't modify any parameter in the code).

**Comment by ewrfcas** [comment]
Sorry for the confusing code. We used --conf for T&T and --prob_threshold for DTU. I will unify them latter.

**Comment by ewrfcas** [comment]
Codes are updated.

**Comment by CC9310** [comment]
> Codes are updated.

it's very kind of you :-)

**Comment by kk6398** [comment]
> 
Hello, I try to use the method that you said, but it occurs an error:"AssertionError: Configuration file need to be specified. Add '-c config.json', for example."      What should I do?

**Comment by mazeyu** [comment]
Hi. I am wondering what is the final prob_threshold/conf in your setting (and possibly other setting changes?). I couldn't find good enough settings. I also asked similar questions in MVSFormer++ repo to reproduce the T&T results.
