### ISSUE TITLE
T&T advanced测试集问题

### ISSUE THREAD

**Issue by kk6398** [ewrfcas/MVSFormer#22]
您好，非常感谢您出色的工作。您在readme文件中提及到T&T intermediate 需要下载short_range_cameras文件，那么有关于advanced测试集呢，我观察到在general_eval.py中，凡是tt测试集，需要寻找short_range_cameras文件，因此我在test advanced时也遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'xxx/tankandtemples/advanced/short_range_cameras/cams_palace/00000000_cam.txt'

**Comment by maybeLx** [comment]
> 

我们README中提供了short_range_cameras 的下载网址，请下载后按照要求放置文件

**Comment by maybeLx** [comment]
> 您好，非常感谢您出色的工作。您在readme文件中提及到T&T intermediate 需要下载short_range_cameras文件，那么有关于advanced测试集呢，我观察到在general_eval.py中，凡是tt测试集，需要寻找short_range_cameras文件，因此我在test advanced时也遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'xxx/tankandtemples/advanced/short_range_cameras/cams_palace/00000000_cam.txt'

我们README中提供了short_range_cameras 的下载网址，请下载后并解压

**Comment by kk6398** [comment]
> > 您好，非常感谢您出色的工作。您在readme文件中提及到T&T intermediate 需要下载short_range_cameras文件，那么有关于advanced测试集呢，我观察到在general_eval.py中，凡是tt测试集，需要寻找short_range_cameras文件，因此我在test advanced时也遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'xxx/tankandtemples/advanced/short_range_cameras/cams_palace/00000000_cam.txt'
> 
> 我们README中提供了short_range_cameras 的下载网址，请下载后并解压

谢谢。嗯，我已经按照README文件下载并放到了intermediate文件夹下。那么有关于advanced测试集呢？
我观察到在general_eval.py中，凡是tt测试集，需要寻找short_range_cameras文件，因此我在test advanced时也遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'xxx/tankandtemples/advanced/short_range_cameras/cams_palace/00000000_cam.txt'

**Comment by maybeLx** [comment]
> > > 您好，非常感谢您出色的工作。您在readme文件中提及到T&T intermediate 需要下载short_range_cameras文件，那么有关于advanced测试集呢，我观察到在general_eval.py中，凡是tt测试集，需要寻找short_range_cameras文件，因此我在test advanced时也遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'xxx/tankandtemples/advanced/short_range_cameras/cams_palace/00000000_cam.txt'
> > 
> > 
> > 我们README中提供了short_range_cameras 的下载网址，请下载后并解压
> 
> 谢谢。嗯，我已经按照README文件下载并放到了intermediate文件夹下。那么有关于advanced测试集呢？ 我观察到在general_eval.py中，凡是tt测试集，需要寻找short_range_cameras文件，因此我在test advanced时也遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'xxx/tankandtemples/advanced/short_range_cameras/cams_palace/00000000_cam.txt'

这个其实是yaoyao 在issue上发的，他们也只提供了intermediate，没有advance

**Comment by maybeLx** [comment]
> > > 您好，非常感谢您出色的工作。您在readme文件中提及到T&T intermediate 需要下载short_range_cameras文件，那么有关于advanced测试集呢，我观察到在general_eval.py中，凡是tt测试集，需要寻找short_range_cameras文件，因此我在test advanced时也遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'xxx/tankandtemples/advanced/short_range_cameras/cams_palace/00000000_cam.txt'
> > 
> > 
> > 我们README中提供了short_range_cameras 的下载网址，请下载后并解压
> 
> 谢谢。嗯，我已经按照README文件下载并放到了intermediate文件夹下。那么有关于advanced测试集呢？ 我观察到在general_eval.py中，凡是tt测试集，需要寻找short_range_cameras文件，因此我在test advanced时也遇到了问题：FileNotFoundError: [Errno 2] No such file or directory: 'xxx/tankandtemples/advanced/short_range_cameras/cams_palace/00000000_cam.txt'

这个short_range_cameras 是yaoyao在mvsnet 的issue中上传的文件夹，他们也只提供了intermediate，没有advance
