### ISSUE TITLE
关于T&T advanced 数据集测试的问题

### ISSUE THREAD

**Issue by crazydiamondaz** [ewrfcas/MVSFormer#27]
首先感谢作者出色的工作！
我采用了如下命令来测试：
CUDA_VISIBLE_DEVICES=0 python test.py --dataset tt --batch_size 1 \
                                      --testpath /CFSDATA/advanced \
                                      --testlist ./lists/tanksandtemples/advanced.txt \
                                      --resume /MVSFormer_try0/weight/best.pth \
                                      --outdir /CFSDATA/result_advanced/ \ 
                                      --interval_scale 1.0 --num_view 10 --numdepth 256 \
                                      --max_h 512 --max_w 640 --filter_method dpcd \
                                      --prob_threshold 0.5,0.5,0.5,0.5 \
                                      --combine_conf --tmps 5.0,5.0,5.0,1.0
去掉了--use_short_range选项来测试advanced数据集效果，发现advanced数据集生成的.pfm文件转换成图像后的深度效果（有一大部分的深度图都是这样的单值图像）很差：
![00000000](https://github.com/ewrfcas/MVSFormer/assets/46803604/2ab9af06-b510-4d55-826c-ff775f71b1e0)
与此同时，当我生成Temple时无论分辨率是什么都会有以下报错：
![image](https://github.com/ewrfcas/MVSFormer/assets/46803604/599dd56c-7770-4837-af79-b0450882953e)
感谢任何帮助

**Comment by ewrfcas** [comment]
可能是因为depth的问题导致点云生成失败。可能要首先验证相机位姿读取和处理是否正确。

**Comment by crazydiamondaz** [comment]
> 可能是因为depth的问题导致点云生成失败。可能要首先验证相机位姿读取和处理是否正确。

谢谢您迅速的回复，您使用的数据集所使用的pairs.txt是经过预处理的吗（不是T&T数据集自带的）？我看好像是pairs.txt由于view的数量改变而生成出错。再次感谢您的回复。

**Comment by crazydiamondaz** [comment]
> > 可能是因为depth的问题导致点云生成失败。可能要首先验证相机位姿读取和处理是否正确。
> 
> 谢谢您迅速的回复，您使用的数据集所使用的pairs.txt是经过预处理的吗（不是T&T数据集自带的）？我看好像是pairs.txt由于view的数量改变而生成出错。再次感谢您的回复。

这个pairs.txt好像是MVSNet里YOYO提供的，在他提供的pairs.txt中有一部分的reference view少于10个，导致出现了这个问题
