### ISSUE TITLE
does someone know what "DPCD" and "PCD" filters stand for ?

### ISSUE THREAD

**Issue by karimcossentini** [ewrfcas/MVSFormer#29]

**Comment by ewrfcas** [comment]
We use DPCD to avoid hyper-parameter tunings for T&T reconstruction.

**Comment by karimcossentini** [comment]
> We use DPCD to avoid hyper-parameter tunings for T&T reconstruction.

I think it is something similar to Gipuma right ? can you provide me with any resource or references about DPCD please. Thanks

**Comment by ewrfcas** [comment]
> > We use DPCD to avoid hyper-parameter tunings for T&T reconstruction.
> 
> I think it is something similar to Gipuma right ? can you provide me with any resource or references about DPCD please. Thanks

Sure, you could find DPCD in the paper called "Dense hybrid recurrent multi-view stereo net with dynamic consistency" (ECCV2020).

https://github.com/yhw-yhw/D2HC-RMVSNet

**Comment by karimcossentini** [comment]
> Dense hybrid recurrent multi-view stereo net with dynamic consistency

Thanks :)
