### ISSUE TITLE
missing keys when load 'alt_gvt_small.pth'

### ISSUE THREAD

**Issue by monoavatar** [ewrfcas/MVSFormer#4]
hi, thanks for your work.

When I load the pretrained Twins weights, I meet the problem `missing keys:['norm_list.0.weight', 'norm_list.0.bias', 'norm_list.1.weight', 'norm_list.1.bias', 'norm_list.2.weight', 'norm_list.2.bias', 'norm_list.3.weight', 'norm_list.3.bias']`. Is this message normal? And will this error affect the performance?

Looking forward to your reply.

**Comment by ewrfcas** [comment]
```norm_list``` is not in pretrained Twins, but it should be finetuned for the downstream task.
