### ISSUE TITLE
missing "short_range_cameras" in tt dataset

### ISSUE THREAD

**Issue by zhangguanghui1** [ewrfcas/MVSFormer#5]
Hi, great work！Where is "short_range_cameras"? could you share it?

**Comment by ewrfcas** [comment]
I remember that "short_range_cameras" is included in the MVSNet preprocessed Tanks&Temples' link, which is also shared in our readme https://drive.google.com/open?id=1YArOJaX9WVLJh4757uE8AEREYkgszrCo.
You can check for it.

**Comment by maybeLx** [comment]
The original link of `short_range_caemeras_for_mvsnet.zip` is expired ，we have uploaded to google driver, you can download it here ,https://drive.google.com/file/d/1Nbsq3WEVSg9tppMjN6hYM_rzuALWnrIy/view?usp=sharing,
