### ISSUE TITLE
MVSFormer-H 测试

### ISSUE THREAD

**Issue by lt-xiang** [ewrfcas/MVSFormer#9]
您好，我这边在测试MVSFormer-H 这块时，发现如下问题，请问可以帮忙看一下吗？

![1](https://user-images.githubusercontent.com/27660078/224175318-19d2c17a-e652-45f9-8229-9457fb229e99.JPG)

**Comment by ewrfcas** [comment]
应该是timm版本问题，可以检查下

**Comment by pang-xiang** [comment]
这个确实是timm版本问题，参照 #3 不换版本解决
